server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

app:
  hot-products:
    l2:
      ttl-seconds: 30
      jitter-seconds: 10
    mutex:
      lock-ttl-ms: 3000
      retry-times: 6
      retry-base-sleep-ms: 40
      retry-max-sleep-ms: 200
